
[options]
addons_path = C:\Odoo\odoo\addons,C:\Odoo\tutorials
;C:\Dev\enterprise,C:\Dev\design-themes
; ,C:\Users\EdEtNinon\PycharmProjects\edi_platform
db_port = 5432
db_user = OdooTutorialAwesome
db_name = Tutorial_Awesome_Owl
db_password = PSpsai43*
bin_path = C:\Program Files\wkhtmltopdf\bin
;admin_passwd = $pbkdf2-sha512$25000$997735vz/p9Tao0RQoiRkg$XHys.IL7ZmtleCJNlDHfI6CZe7YIZngjUTZbMJxP8ZcW2yGqXNKC0XkUVslePYfdroNlMsWKu7dt0ajB18SgMA
; log_handler= :INFO